
package artifact;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "MyServiceSOAP", targetNamespace = "http://book/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyServiceSOAP {


    /**
     * 
     * @return
     *     returns java.util.List<artifact.Researcher>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfotmationAboutResearchers", targetNamespace = "http://book/", className = "artifact.GetInfotmationAboutResearchers")
    @ResponseWrapper(localName = "getInfotmationAboutResearchersResponse", targetNamespace = "http://book/", className = "artifact.GetInfotmationAboutResearchersResponse")
    public List<Researcher> getInfotmationAboutResearchers();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<artifact.Researcher>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfotmationAboutResearchersByName", targetNamespace = "http://book/", className = "artifact.GetInfotmationAboutResearchersByName")
    @ResponseWrapper(localName = "getInfotmationAboutResearchersByNameResponse", targetNamespace = "http://book/", className = "artifact.GetInfotmationAboutResearchersByNameResponse")
    public List<Researcher> getInfotmationAboutResearchersByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<artifact.Researcher>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfotmationAboutResearchersByInterest", targetNamespace = "http://book/", className = "artifact.GetInfotmationAboutResearchersByInterest")
    @ResponseWrapper(localName = "getInfotmationAboutResearchersByInterestResponse", targetNamespace = "http://book/", className = "artifact.GetInfotmationAboutResearchersByInterestResponse")
    public List<Researcher> getInfotmationAboutResearchersByInterest(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
